# Generated by Django 4.1.7 on 2023-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_name', models.CharField(max_length=100, verbose_name='Chair name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('pic', models.ImageField(upload_to='', verbose_name='Picture')),
            ],
        ),
    ]
