# Generated by Django 4.1.7 on 2023-03-22 17:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chairs_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_id', models.IntegerField(verbose_name='Chair id')),
                ('user_id', models.IntegerField(verbose_name='User id')),
                ('chair_amount', models.IntegerField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('city', models.IntegerField(verbose_name='City')),
                ('street', models.IntegerField(verbose_name='Street')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('house', models.IntegerField(verbose_name='House')),
                ('apartment', models.IntegerField(verbose_name='Apartment')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfos',
            },
        ),
    ]
