# Generated by Django 4.1.7 on 2023-03-22 17:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
