# Generated by Django 4.1.7 on 2023-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userinformation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='city',
            field=models.CharField(choices=[('spb', 'Saint-Petersburg'), ('msk', 'Moscow'), ('smr', 'Samara'), ('kzn', 'Kazan')], default='green', max_length=25),
        ),
    ]
