# Generated by Django 4.1.7 on 2023-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userinformation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
    ]
