# Generated by Django 4.1.7 on 2023-03-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userinformation_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairs',
            name='mini_pic',
            field=models.ImageField(default='null', upload_to='static/main/img/', verbose_name='Small Picture'),
        ),
    ]
